# Generated by Django 4.1.7 on 2024-01-21 14:56

import api.models
from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alumni",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=225, verbose_name="Alumni's Name"),
                ),
                (
                    "passing_year",
                    models.IntegerField(verbose_name="Alumni's Passing Year"),
                ),
                (
                    "division",
                    models.CharField(
                        choices=[
                            ("Competitive Programming", "Competitive Programming"),
                            ("Cyber Security", "Cyber Security"),
                            ("Software Development", "Software Development"),
                        ],
                        max_length=225,
                        verbose_name="Alumni's Division",
                    ),
                ),
                (
                    "image",
                    django_resized.forms.ResizedImageField(
                        crop=None,
                        force_format="WEBP",
                        keep_meta=True,
                        quality=100,
                        scale=None,
                        size=[1920, 1080],
                        upload_to=api.models.alumni_path,
                        verbose_name="Image",
                    ),
                ),
                (
                    "LinkedIn_Profile",
                    models.URLField(verbose_name="Alumni's LinkedIn Profile"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        max_length=225,
                        null=True,
                        verbose_name="Event Title",
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, max_length=225, null=True, verbose_name="Subtitle"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("aUpcoming", "Upcoming"),
                            ("bOngoing", "Ongoing"),
                            ("cPast", "Past"),
                        ],
                        max_length=225,
                        null=True,
                        verbose_name="Type",
                    ),
                ),
                (
                    "image",
                    django_resized.forms.ResizedImageField(
                        crop=None,
                        force_format="WEBP",
                        keep_meta=True,
                        quality=100,
                        scale=None,
                        size=[1920, 1080],
                        upload_to=api.models.event_path,
                        verbose_name="Poster",
                    ),
                ),
            ],
            options={
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        max_length=225,
                        null=True,
                        verbose_name="Project Title",
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        blank=True,
                        max_length=225,
                        null=True,
                        verbose_name="Project Subtitle",
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        blank=True, max_length=225, null=True, verbose_name="Domain"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, max_length=225, null=True, verbose_name="Category"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "image",
                    django_resized.forms.ResizedImageField(
                        crop=None,
                        force_format="WEBP",
                        keep_meta=True,
                        quality=100,
                        scale=None,
                        size=[1920, 1080],
                        upload_to=api.models.project_path,
                        verbose_name="Image",
                    ),
                ),
                (
                    "github",
                    models.URLField(blank=True, null=True, verbose_name="Repository"),
                ),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
                "ordering": ("-category",),
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=225, null=True, verbose_name="Name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("aPresident", "President"),
                            ("bMember", "Member"),
                            ("cVolunteer", "Volunteer"),
                        ],
                        max_length=225,
                        null=True,
                        verbose_name="Position",
                    ),
                ),
                (
                    "division",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("aCompetitive Programming", "Competitive Programming"),
                            ("cCyber Security", "Cyber Security"),
                            ("bSoftware Development", "Software Development"),
                        ],
                        max_length=225,
                        null=True,
                        verbose_name="Division",
                    ),
                ),
                (
                    "year",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("First", "First"),
                            ("Second", "Second"),
                            ("Third", "Third"),
                            ("Fourth", "Fourth"),
                        ],
                        max_length=10,
                        null=True,
                        verbose_name="Year",
                    ),
                ),
                (
                    "github",
                    models.URLField(
                        blank=True, null=True, verbose_name="GitHub Profile"
                    ),
                ),
                (
                    "codeforces",
                    models.URLField(
                        blank=True, null=True, verbose_name="Codeforces Profile"
                    ),
                ),
                (
                    "linkedin",
                    models.URLField(
                        blank=True, null=True, verbose_name="LinkedIn Profile"
                    ),
                ),
                (
                    "image",
                    django_resized.forms.ResizedImageField(
                        crop=None,
                        force_format="WEBP",
                        keep_meta=True,
                        quality=100,
                        scale=None,
                        size=[1920, 1080],
                        upload_to=api.models.team_path,
                        verbose_name="Image",
                    ),
                ),
                (
                    "instagram",
                    models.URLField(
                        blank=True, null=True, verbose_name="Instagram Profile"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=225,
                        null=True,
                        verbose_name="Phone Number",
                    ),
                ),
            ],
            options={
                "verbose_name": "Member",
                "verbose_name_plural": "Team",
            },
        ),
    ]
