# Generated by Django 4.1.4 on 2023-03-09 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='codeforces_profile_link',
            field=models.URLField(default='a'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='division',
            field=models.CharField(choices=[('Competitive Programming', 'Competitive Programming'), ('Cyber Security', 'Cyber Security'), ('Software Development', 'Software Development')], default='a', max_length=225),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='github_profile_link',
            field=models.URLField(default='a'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='linkedIn_profile_link',
            field=models.URLField(default='a'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='position',
            field=models.CharField(choices=[('President', 'President'), ('Member', 'Member'), ('Volunteer', 'Volunteer')], default='a', max_length=225),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='year',
            field=models.CharField(choices=[('First', 'First'), ('Second', 'Second'), ('Third', 'Third'), ('Fourth', 'Fourth')], default='a', max_length=10),
            preserve_default=False,
        ),
    ]
