# Generated by Django 4.1.7 on 2023-03-22 07:00

import api.models
from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225, verbose_name="Alumni's Name")),
                ('passing_year', models.CharField(max_length=225, verbose_name="Alumni's Passing Year")),
                ('division', models.CharField(choices=[('Competitive Programming', 'Competitive Programming'), ('Cyber Security', 'Cyber Security'), ('Software Development', 'Software Development')], max_length=225, verbose_name="Alumni's Division")),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to=api.models.alumni_path, verbose_name='Image')),
                ('LinkedIn_Profile', models.URLField(verbose_name="Alumni's LinkedIn Profile")),
            ],
        ),
    ]
