# Generated by Django 4.1.7 on 2023-05-27 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='division',
            field=models.CharField(choices=[('aCompetitive Programming', 'Competitive Programming'), ('cCyber Security', 'Cyber Security'), ('bSoftware Development', 'Software Development')], max_length=225, verbose_name='Division'),
        ),
        migrations.AlterField(
            model_name='team',
            name='position',
            field=models.CharField(choices=[('aPresident', 'President'), ('bMember', 'Member'), ('cVolunteer', 'Volunteer')], max_length=225, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='team',
            name='year',
            field=models.CharField(choices=[('First', 'First'), ('Second', 'Second'), ('Third', 'Third'), ('Fourth', 'Fourth')], max_length=10, verbose_name='Year'),
        ),
    ]
