# Generated by Django 4.1.7 on 2023-05-27 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_team_division_alter_team_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('aUpcoming', 'Upcoming'), ('bOngoing', 'Ongoing'), ('cPast', 'Past')], max_length=225, verbose_name='Type'),
        ),
    ]
