# Generated by Django 4.1.4 on 2023-03-09 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_contact_codeforces_profile_link_contact_division_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='subtitle',
            field=models.CharField(default='a', max_length=225),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='project_state',
            field=models.CharField(choices=[('Ongoing', 'Ongoing'), ('Completed', 'Completed')], default='a', max_length=225),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(default='a', max_length=225),
            preserve_default=False,
        ),
    ]
