# Generated by Django 4.1.7 on 2023-03-22 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alumni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='passing_year',
            field=models.IntegerField(verbose_name="Alumni's Passing Year"),
        ),
    ]
