# Generated by Django 4.1.7 on 2023-03-28 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_alumni_passing_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='subtitle',
            field=models.CharField(default='', max_length=225, verbose_name='Project Subtitle'),
            preserve_default=False,
        ),
    ]
