# Generated by Django 4.1.7 on 2023-03-09 08:03

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_remove_contact_codeforces_profile_link_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=225, verbose_name="Name")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("President", "President"),
                            ("Member", "Member"),
                            ("Volunteer", "Volunteer"),
                        ],
                        max_length=225,
                        verbose_name="Position",
                    ),
                ),
                (
                    "division",
                    models.CharField(
                        choices=[
                            ("Competitive Programming", "Competitive Programming"),
                            ("Cyber Security", "Cyber Security"),
                            ("Software Development", "Software Development"),
                        ],
                        max_length=225,
                        verbose_name="Division",
                    ),
                ),
                (
                    "year",
                    models.CharField(
                        choices=[
                            ("First", "First"),
                            ("Second", "Second"),
                            ("Third", "Third"),
                            ("Fourth", "Fourth"),
                        ],
                        max_length=10,
                        verbose_name="Year",
                    ),
                ),
                ("github", models.URLField(verbose_name="GitHub Profile")),
                ("codeforces", models.URLField(verbose_name="Codeforces Profile")),
                ("linkedin", models.URLField(verbose_name="LinkedIn Profile")),
                (
                    "image",
                    models.ImageField(
                        upload_to=api.models.image_path, verbose_name="Image"
                    ),
                ),
            ],
            options={
                "verbose_name": "Team",
                "verbose_name_plural": "Teams",
            },
        ),
        migrations.DeleteModel(
            name="Contact",
        ),
        migrations.AlterModelOptions(
            name="event",
            options={"verbose_name": "Event", "verbose_name_plural": "Events"},
        ),
        migrations.AlterModelOptions(
            name="project",
            options={
                "ordering": ("-category",),
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
            },
        ),
    ]
