# Generated by Django 4.1.7 on 2023-03-20 09:59

import api.models
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_alter_team_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="image",
            field=django_resized.forms.ResizedImageField(
                crop=None,
                force_format="WEBP",
                keep_meta=True,
                quality=100,
                scale=None,
                size=[1920, 1080],
                upload_to=api.models.blog_path,
                verbose_name="Poster",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="image",
            field=django_resized.forms.ResizedImageField(
                crop=None,
                force_format="WEBP",
                keep_meta=True,
                quality=100,
                scale=None,
                size=[1920, 1080],
                upload_to=api.models.project_path,
                verbose_name="Image",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="image",
            field=django_resized.forms.ResizedImageField(
                crop=None,
                force_format="WEBP",
                keep_meta=True,
                quality=100,
                scale=None,
                size=[1920, 1080],
                upload_to=api.models.image_path,
                verbose_name="Image",
            ),
        ),
    ]
